services:
  emporio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: luxtjbe_emporio
    image: ghcr.io/kuunalroychoudhury/luxtj/emporio:latest
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    # command: uvicorn --factory --host 0.0.0.0 --port 8000 emporio.core.main:application_factory
    command: uvicorn --factory --host 0.0.0.0 --port 8000 emporio.core.main:application_factory
    networks:
      - luxtj_be

networks:
  luxtj_be:
    external: true
