[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "luxtj_be"
version = "0.1.0"
description = "Backend for Luxe Travel Jaunts"
authors = [
    { name="Kuunal Roychoudhury", email="lanuks97@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"

dependencies = [
    "fastapi==0.115.*",
    # ruff==0.11.*
    "uvicorn==0.34.*",
    "sqlalchemy[asyncio]==2.*",
    "asyncpg==0.30.*",
]

[tool.ruff]
line-length = 80
